# Created for dcpd

[info]

website = "https://pkg.devcairo.xyz"
authors = "DevCairo, Jake"
config = "config.cfg"
license = "GPL v3"
dob = "2021-05-18"
version = 2021.1

[mirrors]
server = "https://mirrors.devcairo.xyz/{os}/{arch}/{file}"

